### ISSUE TITLE
Question: Can this free version with login and register be used in commercial app?

### ISSUE THREAD

**Issue by entrptaher** [creativetimofficial/material-dashboard-react-nodejs#1]
I just went through the code and demo and saw it has login and registration page inside as well. 

All other demo stated that the login/registration is part of pro version.

But, since it's already part of free version, can this be used for commercial usage?

Thanks

**Comment by TyMick** [comment]
I see no unique license information in [LoginPage.jsx](https://github.com/creativetimofficial/material-dashboard-react-nodejs/blob/master/material-dashboard-react-app/src/views/Pages/LoginPage.jsx) or [RegisterPage.jsx](https://github.com/creativetimofficial/material-dashboard-react-nodejs/blob/master/material-dashboard-react-app/src/views/Pages/RegisterPage.jsx), so I assume the MIT licenses [in the root folder](https://github.com/creativetimofficial/material-dashboard-react-nodejs/blob/master/LICENSE.md) and [in the material-dashboard-react folder](https://github.com/creativetimofficial/material-dashboard-react-nodejs/blob/master/material-dashboard-react-app/LICENSE.md) apply, which would mean commercial usage is fine.
