### ISSUE TITLE
[Bug] Login not working on live preview

### ISSUE THREAD

**Issue by einazare** [creativetimofficial/material-dashboard-react-nodejs#4]
### Version
live preview version
### Reproduction link
https://www.creative-tim.com/live/material-dashboard-react-nodejs
### Operating System
Does not matter
### Device
Does not matter
### Browser & Version
Does not matter
### Steps to reproduce
1. Go on the link provided above.
2. Try to login using the given credentials (Email: admin@material.com, Password: secret).
3. Login does not work as if the credentials are wrong.
### What is expected?
Login working properly on the live preview.
### What is actually happening?
Login **NOT** working properly on the live preview.

---
### Solution
No solution at the moment.
### Additional comments
Please leave a comment here when the issue is solved.

**Comment by giorgimode** [comment]
same issue, did you ever fix this?
