### ISSUE TITLE
Hello everything is deprecated and impossible to install (french new dev ^^)

### ISSUE THREAD

**Issue by Metalz** [creativetimofficial/material-dashboard-react-nodejs#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by mohamadrezahedayat** [comment]
when wnat to install api this error throws
npm ERR! code 1
npm ERR! path C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\node-sassnpm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\hedi\\Desktop\\material-dashboard-react-nodejs-master\\material-dashboard-api\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Program Files\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:450:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hedi\\Desktop\\material-dashboard-react-nodejs-master\\material-dashboard-api\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\hedi\Desktop\material-dashboard-react-nodejs-master\material-dashboard-api\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
