### ISSUE TITLE
Problem with "npm run build"

### ISSUE THREAD

**Issue by gabrieltorreswm** [creativetimofficial/material-dashboard-react-nodejs#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [* ] I am running the latest version
- [*] I checked the documentation and found no answer
- [ *] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
That when I run "npm run build" it's created that folder etc....

# Current Behavior

When try run the next command 
"npm run build"  then in console show the next message

<img width="707" alt="Screen Shot 2020-04-12 at 18 03 49" src="https://user-images.githubusercontent.com/9329001/79081994-fb157b00-7ce7-11ea-9275-7c80f06226f8.png">
 

What is the current behavior?

Cannot find module: 'layouts/Admin.jsx'. Make sure this package is installed.

You can install this package by running: npm install layouts/Admin.jsx.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: 
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by chosenvictim** [comment]
Somehow this project isn't' able to pickup .env files data
You can solve this issue by passing NODE_ENV=./src in package.json scripts
Example:
`"start:dev": "NODE_ENV=./src react-scripts start"`
